sudo: false
dist: trusty
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install
  - rm -rf build
  - rm -rf dist
  - rm -rf pylint_runner.egg-info

script:
  - nosetests -v --with-coverage --cover-package=pylint_runner
  - pylint_runner

after_success:
  - coveralls

deploy:
  on:
    tags: true
    python: '3.6'
  provider: pypi
  distributions: 'bdist_wheel sdist'
  user: Master_Odin_Bot
  repo: MasterOdin/pylint_runner
  password:
    secure: NA6DRE/llIT1LhMu5JlYMH8yShAI3qpAVCasYpfCncRnChY7Cr5fRI4eEW465T0xQLXNKEQod3pRvmCWFtAKTtHx7Eqkf2+lZlK7bO0ToYrJ8QL3lAl3EY9UpQDBNtECc2/6ctROND2UqqifZkuHUKvNHc3qsjTGDAeFzvPQxj4=  

notifications:
  email:
    - on_failure: change
    - on_success: change
